### ISSUE TITLE
Positioning with new CSS changes

### ISSUE THREAD

**Issue by selfup** [selfup/hyperapp-one#11]
<img width="1920" alt="screen shot 2017-02-18 at 3 15 58 pm" src="https://cloud.githubusercontent.com/assets/9837366/23097281/32714cc6-f5ed-11e6-8167-df8ab69dadb6.png">

@lukejacksonn ^ ^

**Comment by lukejacksonn** [comment]
Was afk yesterday.. what is the issue here? I like your setup!

**Comment by selfup** [comment]
haha thanks! It just seems like there is a bit more padding than necessary on top. Could just be me though 😂
