### ISSUE TITLE
Add minification plugin?

### ISSUE THREAD

**Issue by jbucaran** [selfup/hyperapp-one#2]
I guess we could go on and on with plugins to recommend, but it should feature at least a way to mangle and minify the code.

Side note: What about tree shaking? Does it work OTTB in Webpack@2?

**Comment by selfup** [comment]
I could take a look if you want! Then it wouldn't be such a simple repo though haha.

I am trying to keep things as simple as possible so that people can integrate what they want afterwards.

I will look into minifying the code (which would have to happen in bundle.js as well)

**Comment by selfup** [comment]
Ok check out #6 now I got to bed!

**Comment by jbucaran** [comment]
Awesome! Thanks @selfup.

No, need to get fancy, but if the user is already dabbling with webpack, might as well use the babili or something to minify.

Looking good.

**Comment by selfup** [comment]
👍
