### ISSUE TITLE
Consider removing unused files from the main repo.

### ISSUE THREAD

**Issue by jbucaran** [selfup/hyperapp-one#3]
For example bundle.js and bundle.css.

**Comment by selfup** [comment]
So they are used when you `npm run build` for gh-pages. Let me see if removing them works in dev mode.

**Comment by selfup** [comment]
@jbucaran Ok it seems to work fine with `npm start` without the files. Then they build fine with `npm run build` 🎉

**Comment by jbucaran** [comment]
Didn't notice you where using gh-pages either. Cool!
