### ISSUE TITLE
Upgrade to webpack v4 once it comes out (really soon!)

### ISSUE THREAD

**Issue by selfup** [selfup/hyperapp-one#36]
# Reasons

1. Less config
2. Better performance
3. Stay up to date

### Where is webpack 4 being tracked?

Right here! https://github.com/webpack/webpack/milestone/15

**Comment by diomed** [comment]
why weback @ all?
Why not switch to [Parcel](https://parceljs.org/)

**Comment by selfup** [comment]
Because Webpack has professional support, is used by giants like GitLab/AirBnb/Facebook/etc, provides code splitting (mature), and many other features 😄

Webpack works, no need to switch to something else 🚀

**Comment by selfup** [comment]
@diomed I made this for ya: https://github.com/selfup/hyperapp-one-parcel

I will add testing to it and change the `src` structure so the view can be tested, but here is a good example on how to use parcel with HA!

**Comment by diomed** [comment]
I can't believe you made this for me 😱 
Thank you very much. 👍 
I'm stunned.

**Comment by selfup** [comment]
Also just added support for gh-pages via a custom script in the package.json: https://github.com/selfup/hyperapp-one-parcel/issues/1 🎉

**Comment by selfup** [comment]
Only update to 3.11, once Hyperapp 2 is out, will switch to parcel
