### ISSUE TITLE
Use hyperapp/hyperxify to remove Hyperx from bundle and transform template functions to raw h calls

### ISSUE THREAD

**Issue by jbucaran** [selfup/hyperapp-one#4]
Will involve including the [transform loader](https://github.com/webpack-contrib/transform-loader) as well.

This will improve performance by transpiling 

```
html`<h1>Hi</h1>`
```

into
```
h("h1", {}, ["Hi"])
```

and also by removing the entire hyperx code from the result bundle.

* Depends on https://github.com/substack/hyperxify/pull/8.

**Comment by selfup** [comment]
Maybe we could add in the README what needs to be done?

This repo should allow people to either use JSX or tagged template literals.

What do you think?

**Comment by jbucaran** [comment]
I assumed you'd only wanted to use Hyperx, but now in hindsight, when you created the repo there was no JSX support yet, so you really didn't have a choice. 

Yes, I think users should be able to decide what they want to use.

I'm writing the instructions here for the record, and incrementally support either one and eventually both.

For **Hyperx** users need to use browserify with hyperxify (when it's merged, or alternatively our own fork if it doesn't) it will look like this:

```
browserify -t hyperxify -g uglifyify index.js | uglifyjs > bundle.js
```

or if using babel, the transform-loader. You'll have to figure out how the configuration works for that one.

For **JSX** users need to use the pragma:

```
/** @jsx h */
```

or better add to the .babelrc

```
{
  "plugins": [
    ["transform-react-jsx", { "pragma":"h" }]
  ]
}
```

**Comment by selfup** [comment]
Ok I have an idea. What if I switch the repo to use JSX (which is do prefer) so that we can keep everything in the webpack family, and then for users that want to use the `tagged template literals` we can show them in the README the modified package.json they would need (with the script tag included) to rely on `browserify` and those build tools instead?

Just a thought!

Ok now I really need to go haha. We can discuss further tomorrow

**Comment by jbucaran** [comment]
That'd work too. We can create another repo or gist focused in template functions anyway.

**Comment by selfup** [comment]
Ok I have a somewhat frankestein build, but I think it makes sense 😆

**Comment by jbucaran** [comment]
@selfup Does it work?

**Comment by selfup** [comment]
Yes it worked :)

It is much faster now too. I removed some odd steps.

**Comment by jbucaran** [comment]
Are you using hyperapp/hyperxify right?

**Comment by selfup** [comment]
Ohh I am just using hyperxify right now. Sorry about that! I will use the name spaced module. Good catch 😂

**Comment by jbucaran** [comment]
If you are using hyperxify, then it couldn't have possibly worked... 😨

**Comment by selfup** [comment]
Ohh I know why. I was still using JSX 😂

**Comment by selfup** [comment]
Ok I will attempt with

https://gist.github.com/selfup/bbf5c07bbac447e36f7e86f73d29754a

And report back! haha uhh ohh

**Comment by selfup** [comment]
@jbucaran sooo

```
("div",{className:"counter"},(0,r.h)("h1",null,"Welcome to the hyperapp-one boilerplate!"
```

It still transformed some things...

Now I will try with your module

**Comment by selfup** [comment]
### Using substack/hyperxify

<img width="262" alt="screen shot 2017-02-09 at 8 35 43 am" src="https://cloud.githubusercontent.com/assets/9837366/22790489/9ef64b90-eea3-11e6-8f7a-e5fec585f635.png">

### Using hyperapp/hyperxify

<img width="279" alt="screen shot 2017-02-09 at 8 41 31 am" src="https://cloud.githubusercontent.com/assets/9837366/22790534/bdbd54f6-eea3-11e6-97b5-3513b1a7cd23.png">

The `bundle.js` seems to be identical? Am I doing something wrong? Everything "works" though

**Comment by jbucaran** [comment]
@selfup Yes, something does not seem right. We need to inspect the bundle.js to see what's happening.

**Comment by selfup** [comment]
Well let me know. Because for *now* we can at least use the transform and then worry about completely removing hyperx.

What do you think?

**Comment by jbucaran** [comment]
Yes. Is this merged into master already?

**Comment by selfup** [comment]
No not yet. I will change to use your repo instead

**Comment by selfup** [comment]
@jbucaran It has been merged!

**Comment by selfup** [comment]
Closing in favor of JSX only for this repo per this comment: https://github.com/selfup/hyperapp-one/pull/7#issuecomment-278849310

🎉
