### ISSUE TITLE
Updating deps causes install errors

### ISSUE THREAD

**Issue by SteveALee** [selfup/hyperapp-one#45]
I tried updating the deps, many of which are now pretty old, but got a lot of errors. In the end I stopped exploring the reasons

**Comment by selfup** [comment]
I just updated them recently, which ones did you update?

**Comment by SteveALee** [comment]
Ah, I might have been webpack. then

Most others have updates (according to version lens code extension)

**Comment by selfup** [comment]
No worries! In a month or so I'll see if I can move to WP4. Wait for other deps to catch up 👍
